servers:
  performer: localhost
  driver: {hostname: localhost, source: /Users/ronith.jaju/Documents/faasTrial}
database: {hostname: localhost, hostname_docker: timedb, port: 5432, username: postgres,
  password: password, database: perf}
environment: {executables: null, envvar: null, workspace: workspace}
variables: {dryRun: false, force: false, skipDriverDockerBuild: false, skipPerformerDockerBuild: false,
  runsRequired: 1, stopOnFailure: false}
matrix:
  clusters:
  - {type: unmanaged, connection_string_driver: 'couchbase://localhost', connection_string_performer: 'couchbase://localhost',
    hostname: localhost, hostname_docker: cbs, hostname_rest: 'http://localhost:8091',
    connection_string_driver_docker: 'couchbase://cbs', connection_string_performer_docker: 'couchbase://cbs',
    hostname_rest_docker: 'http://cbs:8091', storage: couchstore, replicas: 0}
  implementations:
  - {language: Python, version: snapshot}
  - {language: Scala, version: snapshot}
  workloads:
  - operations:
    - op: get
      bounds: {forSeconds: $forSeconds}
      docLocation: {method: pool, poolSize: $poolSize, poolSelectionStrategy: randomUniform}
    settings:
      variables:
      - {name: poolSize, value: 10000}
    exclude:
    - {gerrit: true}
  - operations:
    - op: get
      bounds: {forSeconds: $forSeconds}
      docLocation: {method: pool, poolSize: $poolSize, poolSelectionStrategy: randomUniform}
    settings:
      variables:
      - {name: poolSize, value: 10000}
      - name: horizontalScaling
        values: [1, 2, 4, 8, 16, 32]
      - name: experimentName
        values: [horizontalScaling]
    include:
    - {version: snapshot}
    exclude:
    - {gerrit: true}
settings:
  grpc: {flowControl: true, batch: 1000, compression: true}
  variables:
  - {name: forSeconds, value: 300}
  - name: horizontalScaling
    values: [1, 20]
  - name: api
    values: [DEFAULT, ASYNC]
  - name: concurrencyMechanism
    type: tunable
    value: multiprocessing
    include:
    - implementation: {language: Python}
projectId: 06214fef-8880-4be8-955b-2413a2d423f2
